version: 2
jobs:
   build:
     docker:
       - image: circleci/ubuntu-server:latest
     steps:
       - checkout
       - run:
         name: Install dependencies
         command: apt-get install git
       - run: ./build-all.sh
