version: 2
jobs:
   build:
     docker:
       - image: ubuntu:18.04
     steps:
       - checkout
       - run: apt update && apt install -y git wget build-essential gcc
       - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
       - run: ./build-all.sh
